export const kvizAdatok = [
  {
    nev: "JavaScript",
    kerdesek: [
      { kerdesSzoveg: "Mit jelent a DOM?", valaszok: [
        { szoveg: "Document Object Model", helyes: true },
        { szoveg: "Data Object Method", helyes: false },
        { szoveg: "Display Object Manager", helyes: false },
        { szoveg: "Digital Output Mode", helyes: false },
      ]},
      { kerdesSzoveg: "Melyik kulcsszóval deklarálunk változót?", valaszok: [
        { szoveg: "let", helyes: true },
        { szoveg: "make", helyes: false },
        { szoveg: "varible", helyes: false },
        { szoveg: "new", helyes: false },
      ]},
      { kerdesSzoveg: "Melyik adattípus?", valaszok: [
        { szoveg: "string", helyes: true },
        { szoveg: "letter", helyes: false },
        { szoveg: "word", helyes: false },
        { szoveg: "sentence", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a console.log() célja?", valaszok: [
        { szoveg: "Kiírás konzolra", helyes: true },
        { szoveg: "Adat mentés", helyes: false },
        { szoveg: "HTML generálás", helyes: false },
        { szoveg: "CSS módosítás", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a typeof operátor?", valaszok: [
        { szoveg: "Típus lekérdezés", helyes: true },
        { szoveg: "Összeadás", helyes: false },
        { szoveg: "Eltárolás", helyes: false },
        { szoveg: "Összehasonlítás", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az array?", valaszok: [
        { szoveg: "Tömb", helyes: true },
        { szoveg: "Sztring", helyes: false },
        { szoveg: "Szám", helyes: false },
        { szoveg: "Objektum kulcs", helyes: false },
      ]},
      { kerdesSzoveg: "Melyik ciklus létezik?", valaszok: [
        { szoveg: "for", helyes: true },
        { szoveg: "repeat", helyes: false },
        { szoveg: "loopit", helyes: false },
        { szoveg: "cycle", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a === operátor?", valaszok: [
        { szoveg: "Szigorú egyenlőség", helyes: true },
        { szoveg: "Összeadás", helyes: false },
        { szoveg: "Kivonás", helyes: false },
        { szoveg: "String összefűzés", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az event?", valaszok: [
        { szoveg: "Esemény", helyes: true },
        { szoveg: "Változó", helyes: false },
        { szoveg: "Fájl", helyes: false },
        { szoveg: "Tömb", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a function?", valaszok: [
        { szoveg: "Függvény", helyes: true },
        { szoveg: "Objektum", helyes: false },
        { szoveg: "Tömb", helyes: false },
        { szoveg: "CSS elem", helyes: false },
      ]},

      // +10
      { kerdesSzoveg: "Mi az let és var közti különbség?", valaszok: [
        { szoveg: "let blokkszintű", helyes: true },
        { szoveg: "nincs különbség", helyes: false },
        { szoveg: "var modernebb", helyes: false },
        { szoveg: "let globális", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az const?", valaszok: [
        { szoveg: "Konstans változó", helyes: true },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Függvény", helyes: false },
        { szoveg: "Objektum", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az arrow function?", valaszok: [
        { szoveg: "Rövid függvény szintaxis", helyes: true },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Objektum", helyes: false },
        { szoveg: "Adattípus", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az NaN?", valaszok: [
        { szoveg: "Nem szám", helyes: true },
        { szoveg: "Null érték", helyes: false },
        { szoveg: "String", helyes: false },
        { szoveg: "Boolean", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a null?", valaszok: [
        { szoveg: "Üres érték", helyes: true },
        { szoveg: "Szám", helyes: false },
        { szoveg: "String", helyes: false },
        { szoveg: "Függvény", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az undefined?", valaszok: [
        { szoveg: "Nincs érték", helyes: true },
        { szoveg: "Null", helyes: false },
        { szoveg: "Szám", helyes: false },
        { szoveg: "String", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az addEventListener?", valaszok: [
        { szoveg: "Esemény kezelő hozzáadás", helyes: true },
        { szoveg: "Adat mentés", helyes: false },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Stílus módosítás", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az JSON?", valaszok: [
        { szoveg: "Adatformátum", helyes: true },
        { szoveg: "Programozási nyelv", helyes: false },
        { szoveg: "CSS", helyes: false },
        { szoveg: "HTML elem", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a push()?", valaszok: [
        { szoveg: "Elem hozzáadása tömbhöz", helyes: true },
        { szoveg: "Elem törlés", helyes: false },
        { szoveg: "Kiírás", helyes: false },
        { szoveg: "Összeadás", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a pop()?", valaszok: [
        { szoveg: "Utolsó elem eltávolítása", helyes: true },
        { szoveg: "Elem hozzáadás", helyes: false },
        { szoveg: "Keresés", helyes: false },
        { szoveg: "Ciklus", helyes: false },
      ]},
    ],
  },

  {
    nev: "PHP",
    kerdesek: [
      { kerdesSzoveg: "Mivel kezdődik egy változó?", valaszok: [
        { szoveg: "$", helyes: true },
        { szoveg: "#", helyes: false },
        { szoveg: "@", helyes: false },
        { szoveg: "&", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a echo?", valaszok: [
        { szoveg: "Kiírás", helyes: true },
        { szoveg: "Változó", helyes: false },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Függvény", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a PHP?", valaszok: [
        { szoveg: "Szerveroldali nyelv", helyes: true },
        { szoveg: "CSS", helyes: false },
        { szoveg: "Java könyvtár", helyes: false },
        { szoveg: "HTML elem", helyes: false },
      ]},
      { kerdesSzoveg: "Melyik ciklus létezik?", valaszok: [
        { szoveg: "foreach", helyes: true },
        { szoveg: "loop", helyes: false },
        { szoveg: "repeat", helyes: false },
        { szoveg: "cycle", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az array?", valaszok: [
        { szoveg: "Tömb", helyes: true },
        { szoveg: "Sztring", helyes: false },
        { szoveg: "Szám", helyes: false },
        { szoveg: "Objektum", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a $_GET?", valaszok: [
        { szoveg: "Adat lekérés", helyes: true },
        { szoveg: "Adat törlés", helyes: false },
        { szoveg: "Adat mentés", helyes: false },
        { szoveg: "CSS", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a isset()?", valaszok: [
        { szoveg: "Ellenőrzi létezik-e", helyes: true },
        { szoveg: "Töröl", helyes: false },
        { szoveg: "Kiír", helyes: false },
        { szoveg: "Másol", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a include?", valaszok: [
        { szoveg: "Fájl beillesztés", helyes: true },
        { szoveg: "Fájl törlés", helyes: false },
        { szoveg: "Kimenet", helyes: false },
        { szoveg: "Ciklus", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a ==?", valaszok: [
        { szoveg: "Összehasonlítás", helyes: true },
        { szoveg: "Összeadás", helyes: false },
        { szoveg: "Kivonás", helyes: false },
        { szoveg: "Törlés", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a session?", valaszok: [
        { szoveg: "Session adat", helyes: true },
        { szoveg: "CSS", helyes: false },
        { szoveg: "HTML", helyes: false },
        { szoveg: "Java", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a $_POST?", valaszok: [
        { szoveg: "Adat küldés", helyes: true },
        { szoveg: "Adat törlés", helyes: false },
        { szoveg: "Kiírás", helyes: false },
        { szoveg: "Ciklus", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a strlen()?", valaszok: [
        { szoveg: "Sztring hossza", helyes: true },
        { szoveg: "Számolás", helyes: false },
        { szoveg: "Kiírás", helyes: false },
        { szoveg: "Törlés", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a . operátor?", valaszok: [
        { szoveg: "String összefűzés", helyes: true },
        { szoveg: "Összeadás", helyes: false },
        { szoveg: "Kivonás", helyes: false },
        { szoveg: "Szorzás", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a function?", valaszok: [
        { szoveg: "Függvény", helyes: true },
        { szoveg: "Változó", helyes: false },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Objektum", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a return?", valaszok: [
        { szoveg: "Visszatérési érték", helyes: true },
        { szoveg: "Kiírás", helyes: false },
        { szoveg: "Törlés", helyes: false },
        { szoveg: "Mentés", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a require?", valaszok: [
        { szoveg: "Fájl kötelező betöltés", helyes: true },
        { szoveg: "Fájl törlés", helyes: false },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Adat mentés", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a count()?", valaszok: [
        { szoveg: "Elemek száma", helyes: true },
        { szoveg: "Összeadás", helyes: false },
        { szoveg: "Kiírás", helyes: false },
        { szoveg: "Törlés", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a empty()?", valaszok: [
        { szoveg: "Üres-e", helyes: true },
        { szoveg: "Létezik-e", helyes: false },
        { szoveg: "Kiír", helyes: false },
        { szoveg: "Másol", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a explode()?", valaszok: [
        { szoveg: "String felbontása", helyes: true },
        { szoveg: "Összefűzés", helyes: false },
        { szoveg: "Kiírás", helyes: false },
        { szoveg: "Törlés", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a implode()?", valaszok: [
        { szoveg: "Tömb összefűzése", helyes: true },
        { szoveg: "Tömb törlés", helyes: false },
        { szoveg: "Számolás", helyes: false },
        { szoveg: "Ciklus", helyes: false },
      ]},
    ],
  },

  {
    nev: "Java",
    kerdesek: [
      { kerdesSzoveg: "Mi a Java?", valaszok: [
        { szoveg: "Programozási nyelv", helyes: true },
        { szoveg: "Weboldal", helyes: false },
        { szoveg: "CSS", helyes: false },
        { szoveg: "HTML", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a main()?", valaszok: [
        { szoveg: "Belépési pont", helyes: true },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Változó", helyes: false },
        { szoveg: "Objektum", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a class?", valaszok: [
        { szoveg: "Osztály", helyes: true },
        { szoveg: "Függvény", helyes: false },
        { szoveg: "Sztring", helyes: false },
        { szoveg: "Tömb", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az objektum?", valaszok: [
        { szoveg: "Osztály példánya", helyes: true },
        { szoveg: "Tömb", helyes: false },
        { szoveg: "String", helyes: false },
        { szoveg: "Ciklus", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a String?", valaszok: [
        { szoveg: "Szöveg", helyes: true },
        { szoveg: "Szám", helyes: false },
        { szoveg: "Objektum", helyes: false },
        { szoveg: "Függvény", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a int?", valaszok: [
        { szoveg: "Egész szám", helyes: true },
        { szoveg: "Sztring", helyes: false },
        { szoveg: "Logikai", helyes: false },
        { szoveg: "Objektum", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a for?", valaszok: [
        { szoveg: "Ciklus", helyes: true },
        { szoveg: "Függvény", helyes: false },
        { szoveg: "Osztály", helyes: false },
        { szoveg: "Típus", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a boolean?", valaszok: [
        { szoveg: "true/false", helyes: true },
        { szoveg: "Szám", helyes: false },
        { szoveg: "String", helyes: false },
        { szoveg: "Array", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a System.out.println?", valaszok: [
        { szoveg: "Kiírás", helyes: true },
        { szoveg: "Olvasás", helyes: false },
        { szoveg: "Törlés", helyes: false },
        { szoveg: "Mentés", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a constructor?", valaszok: [
        { szoveg: "Inicializál", helyes: true },
        { szoveg: "Töröl", helyes: false },
        { szoveg: "Kiír", helyes: false },
        { szoveg: "Ciklus", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az extends?", valaszok: [
        { szoveg: "Öröklődés", helyes: true },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Változó", helyes: false },
        { szoveg: "Metódus", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az interface?", valaszok: [
        { szoveg: "Szerződés", helyes: true },
        { szoveg: "Osztály", helyes: false },
        { szoveg: "Változó", helyes: false },
        { szoveg: "Ciklus", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a this?", valaszok: [
        { szoveg: "Aktuális objektum", helyes: true },
        { szoveg: "Változó", helyes: false },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Szám", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a new?", valaszok: [
        { szoveg: "Objektum létrehozás", helyes: true },
        { szoveg: "Törlés", helyes: false },
        { szoveg: "Kiírás", helyes: false },
        { szoveg: "Ciklus", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a void?", valaszok: [
        { szoveg: "Nincs visszatérési érték", helyes: true },
        { szoveg: "Szám", helyes: false },
        { szoveg: "String", helyes: false },
        { szoveg: "Boolean", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a while?", valaszok: [
        { szoveg: "Ciklus", helyes: true },
        { szoveg: "Függvény", helyes: false },
        { szoveg: "Osztály", helyes: false },
        { szoveg: "Típus", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az if?", valaszok: [
        { szoveg: "Feltétel", helyes: true },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Változó", helyes: false },
        { szoveg: "Objektum", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a switch?", valaszok: [
        { szoveg: "Elágazás", helyes: true },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Szám", helyes: false },
        { szoveg: "String", helyes: false },
      ]},
      { kerdesSzoveg: "Mi a try-catch?", valaszok: [
        { szoveg: "Hibakezelés", helyes: true },
        { szoveg: "Ciklus", helyes: false },
        { szoveg: "Változó", helyes: false },
        { szoveg: "Kiírás", helyes: false },
      ]},
      { kerdesSzoveg: "Mi az ArrayList?", valaszok: [
        { szoveg: "Dinamikus lista", helyes: true },
        { szoveg: "Szám", helyes: false },
        { szoveg: "String", helyes: false },
        { szoveg: "Ciklus", helyes: false },
      ]},
    ],
  },
];